export type rest = {
  UC_SEQ:number,
  MAIN_TITLE:string,
  GUGUN_NM:string,
  LAT:string,
  LNG:string,
  PLACE:string,
  TITLE:string,
  SUBTITLE:string,
  ADDR1:string,
  ADDR2:string,
  CNTCT_TEL:string,
  HOMEPAGE_URL:string,
  USAGE_DAY_WEEK_AND_TIME:string,
  RPRSNTV_MENU:string,
  MAIN_IMG_NORMAL:string,
  MAIN_IMG_THUMB:string,
  ITEMCNTNTS:string
};